version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER:test_user
      - POSTGRES_PASSWORD:test_test
      - POSTGRES_DB:test_db
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./media/:/code/media/
    ports:
      - 80:8000
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  celery_worker:
    build: .
    restart: on-failure
    command: celery -A file_share worker -l info
    ports: []
    depends_on:
      - rabbitmq
      - db
  celery_beat:
    build: .
    restart: on-failure
    command: celery -A file_share beat -l info
    ports: []
    depends_on:
      - rabbitmq
      - db
  rabbitmq:
    image: rabbitmq:3.7.15-alpine
volumes:
  postgres_data: